### ISSUE TITLE
Malfunction of the context menu: "Inspect UI5 control"

### ISSUE THREAD

**Issue by JoseCarlosGZ** [SAP/ui5-inspector#195] opened 2022-09-28 10:11 UTC
Hi there,

I am experiencing an issue with the context menu "Inspect UI5 control". It is supposed the component selected in the view should be automatically highlighted in the XML tree window of the extension but it does not happen.

I have tested the scenario with several Fiori applications and disabling all chrome extensions except "UI5 Inspector" but when I select the context menu option "Inspect UI5 control" over any component, it never discovers the location of that component in the extension's XML tree.

![2022-09-28_11h39_08](https://user-images.githubusercontent.com/22302448/192752008-ef213a54-65a9-4523-a9ed-6bbd9477fe02.png)

Thanks,
José Carlos

**Comment by Frank683** [comment] 2022-09-28 10:40
Duplicate of #184

**Comment by JoseCarlosGZ** [comment] 2022-09-28 10:46
Thanks @Frank683

**Comment by dobrinyonkov** [comment] 2022-10-05 08:17
Hi @JoseCarlosGZ, as described in mentioned issue, this was fixed but not yet released to the chrome web store. To consume the fix earlier, follow the steps described in the duplicated issue. Release to the chrome store is expected soon. 

Kind Regards,
Dobrin

**Closed** 2022-10-05 08:19 UTC
