### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by alancampora** [SAP/ui5-inspector#62] opened 2017-09-19 17:36 UTC
I would like to use the extension with my dark-theme of chrome. Is there any way of creating themes?
Checking the repo, I've seen you have a variables.less with the colors. So it seems that adding a new theme file, and somehow knowing which theme is selected in chrome, could be possible. What do you think?

thanks for making this plugin :D!

**Comment by gluons** [comment] 2017-10-02 03:21
Maybe relate to #60

**Comment by SvetlioSS** [comment] 2018-06-04 14:50
Hi @alancampora we are currently working on the dark theme. I am closing this issue as it is a duplicate of #60

**Closed by SvetlioSS** 2018-06-04 14:50 UTC
Labels: duplicate, enhancement
